[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pic2stl"
version = "10.0.1"
authors = [
  { name="niljub", email="dickergamer@tutanota.com" },
]
description = "img2stl is a Python package that converts images to 3D STL models."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
numpy,
numpy-stl,
pillow,
python-utils,
scipy,
trimesh,
typing-extensions,
]

[project.urls]
Homepage = "https://github.com/niljub/pic2stl/"
Issues = "https://github.com/niljub/pic2stl/issues"
