[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "2d2stl_niljub"
version = "0.0.1"
authors = [
  { name="niljub", email="dickergamer@tutanota.com" },
]
description = "2d2stl is a Python package that converts images to 3D STL models."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"